### ISSUE TITLE
Bot platform compatibility (Facebook, Slack, etc.)

### ISSUE THREAD

**Issue by egtann** [itsabot/itsabot#93]
It'd be great to build an interface that enables communication from Abot via Facebook's Bot platform or any other. Facebook bots, Slack bots, etc. built using Abot would be able to use our language tools, state management, and memory API. They'd also benefit from integrating with the other platforms through user discovery, and by having their users communicate with the bot on the platforms they use already (like Slack).

Whoever wants to tackle this would have to design an interface to communicate with arbitrary HTTP bot platforms (Kik, Facebook, Telegram, Slack, etc.), then implement that interface in a driver for at least one platform--ideally Facebook, but any are helpful.

To get started, take a look at one of the existing interfaces, such as the [SMS interface](https://github.com/itsabot/abot/tree/master/shared/interface/sms). Then see how a driver integrates with it by _implementing_ that SMS interface: [Twilio driver](https://github.com/itsabot/twilio/blob/master/twilio.go).

**Comment by DaleWebb** [comment]
Which release would this feature be aimed for?

**Comment by ankitbansal82** [comment]
I will soon start working on integrating it with telegram.

**Comment by DaleWebb** [comment]
Any particular reason for Telegram over other platforms?

**Comment by egtann** [comment]
@DaleWebb for v0.3, but ASAP 👍🏻

**Comment by ankitbansal82** [comment]
@DaleWebb - I have worked with Telegram before and I need it for the project I have in mind anyways.

@egtann  / @all - 
Telegram provides two means of fetching updates. 
[getting-updates](https://core.telegram.org/bots/api#getting-updates) Long polling and webhooks.
[long-polling](https://core.telegram.org/bots/api#getupdates) Long polling doesn't fits in well with Abot design because it's a blocking call. And more so it will not come via the httprouter routes.

[webhooks](https://core.telegram.org/bots/api#setwebhook) Webhooks seems like the better approach to use and is very similar to SMS driver model
But Telegram only allows HTTPS. 

So can we change Abot http server to accept both http and https connections?

**Comment by ankitbansal82** [comment]
Or i can run the long polling update loop on a separate go routine. What do you guys suggest?

**Comment by egtann** [comment]
Use webhooks. An HTTPS requirement is fine

E




On Sun, Jun 5, 2016 at 10:49 AM -0700, "Ankit Bansal" <notifications@github.com> wrote:












Or i can run the long polling update loop on a separate go routine. What do you guys suggest?

**Comment by DaleWebb** [comment]
I agree with the webhooks.

It would be good to get the interface going, so that anyone can do the other platforms too!  I would imagine that they all communicate in a similar fashion with third-party tools.

**Comment by DaleWebb** [comment]
I'm planning to pick up this task.  For the first plugin, I thought smooch.io would be good, as it can already communicate with other messaging services.

What do you think? :)
